#!/bin/sh
#iptables -I PREROUTING -t nat -s 10.0.0.0/8 -p tcp --dport 3724 -j DNAT --to-destination 10.3.13.29
#iptables -I PREROUTING -t nat -s 10.0.0.0/8 -p tcp --dport 8080 -j DNAT --to-destination 10.3.13.29
#iptables -I PREROUTING -t nat -s 10.0.0.0/8 -p tcp --dport 8085 -j DNAT --to-destination 10.3.13.29
